---
title: "tutorial ggplot2"
author: "Talita Lôbo"
output: html_document
---

```{r, set-options, echo=FALSE, cache=FALSE, warning=FALSE}
library(ggplot2)
library(gridExtra)

source("graphics.R")
options(width = 200)
```

-------------------------------

**GGplot2** é um pacote de visualização de dados que pode ser utilizado junto à ferramenta R. Esta biblioteca é um conjunto de componentes independentes que podem ser aplicados de várias formas, construindo gráficos de maneira incremental. 

*"A general scheme for data visualization which breaks up graphs into semantic components such as scales and layers. Ggplot2 can serve as a replacement for the base graphics in R and contains a number of defaults for web and print display of common scales".*


### Instalação e carregamento do pacote

A instalação e utilização da biblioteca no RStudio é feita da seguinte maneira, respectivamente (retire a #):

```{r,cache=FALSE, warning=FALSE}
#install.packages("ggplot2")

#library(ggplot2)
```


### Criando o primeiro plot

Neste primeiro momento utilizaremos uma base de dados padrão do R, Íris - para mais informações: help(iris).

```{r,cache=FALSE, warning=FALSE}
# Carrega a base de dados em iris
iris <- iris

# Breve sumário sobre os dados
summary(iris)
```


Diferente de outras bibliotecas **ggplot2**, não é verborrágico e a geração dos gráficos utiliza o conceito de camadas. Podemos 'guardar' gráficos em variáveis, adicionar outras camadas, modificar as já existentes e finalmente, plotar o gráfico.  
Para construção dos plots dispomos de elementos gráficos tais como:

- Linhas
- Segmentos de linhas
- Pontos
- Barras
- Textos

E cada um desses elementos possuem suas próprias características (aesthetics). Por exemplo:

* Ponto - **geom_point()**
    + shape - triângulo, círculo, quadrado, ...
* Linhas - **geom_line()**
    + type - fechada, tracejada, ...
    + weight

Então, simplesmente temos:

```{r,cache=FALSE, warning=FALSE, fig.height= 5, fig.width=9}    

a <- ggplot(data=iris, aes(x=Sepal.Length, y=Petal.Length, shape = Species)) 
a <- a + geom_point(size=4)
# Plot do gráfico
a
```

Explicando melhor o comando acima:

* a <- ... : 'Guarda' em a o objeto do plot;

* ggplot(data=iris, ...): Inicia o objeto ggplot e define a base de dados a ser usada naquele plot;

* aes (Aesthetics): Descreve como as variáveis dos dados são mapeadas para elementos visuais. Neste caso o eixo x representará o Tamanho da Sépala (Sepal.Length), o eixo y o Tamanho da Pétala (Petal.Length) e a forma do ponto (shape) dependerá da Espécie (Specie) da flor;

* geom_point(...): Espeficica o tipo de gráfico que estamos construindo, neste caso um gráfico de pontos ou gráfico de dispersão - scatterplot;

* Utilizando o operador '+' pode-se adicionar camadas ao objeto ggplot criado acima;

> "The first argument to ggplot() is a data frame (it must be a data frame), and its second argument is aes(). It might be best not to think of aes() as its own function, but rather as a special way of defining data-to-aesthetic mappings."

Como incremento do gráfico acima podemos também definir labels para os eixos, cores, titulo, dentre outras propriedades. 

```{r,cache=FALSE, warning=FALSE, fig.height= 5, fig.width=9}    

# ggplot(data=iris, aes(x=Sepal.Length, y=Petal.Length, shape = Species)) + geom_point(size=4, aes(colour=Species)) + xlab("Tamanho da Sépala") + ylab("Tamanho da Pétala") + ggtitle("Íris")

# Ou 

# ggplot(data=iris, aes(x=Sepal.Length, y=Petal.Length, shape = Species, col = Species)) + geom_point(size=4, aes(colour=Species)) + xlab("Tamanho da Sépala") + ylab("Tamanho da Pétala") + ggtitle("Íris")

# No caso em que utilizemos várias camadas como a 'geom_point()' é necessário que informemos novamente quem serão os eixos x e y, por exemplo:

ggplot(iris) + geom_point(aes(x=Sepal.Length, y=Petal.Length)) + geom_point(size=4, aes(x=Sepal.Length, y=Petal.Length, col=Species, shape=Species)) + xlab("Tamanho da Sépala") + ylab("Tamanho da Pétala") + ggtitle("Íris")

# Podemos até mesmo transformar variáveis diretamente no próprio ggplot2 (repare na escala)

ggplot(iris) + geom_point(aes(x=log(Sepal.Length), y=Petal.Length*10, shape = Species, colour=Species), size=5, alpha=0.5) + xlab("Tamanho da Sépala") + ylab("Tamanho da Pétala") + ggtitle("Íris") 

```


Outra forma de analisar nossos dados é separá-los em gráficos distintos, para tanto podemos utilizar **facets**, isso nos dará vários plots.

```{r,cache=FALSE, warning=FALSE, fig.height= 5, fig.width=9}  

ggplot(iris, aes(x=Sepal.Length, y=Petal.Length, col=Species, shape=Species)) + geom_point(size=4, alpha=0.4) + facet_wrap(~Species) + xlab("Tamanho da Sépala") + ylab("Tamanho da Pétala") + ggtitle("Espécies ~ Íris")

```

***
Acima demonstramos apenas como se dá a construção de gráficos que não necessariamente passam alguma informação.  
*Na construção de gráficos é importante identificar qual pergunta queremos responder com aquela representação e quais informações da base de dados utilizar para melhor responder essa pergunta. A escolha do(s) elemento(s) geométrico(s) utilizados deverá ser baseada na resposta que desejamos proporcionar.*  
Nos exemplos abaixo veremos outros tipos de gráfico e como construí-los.


### Outros exemplos

Utilizaremos também uma outra base de dados padrão do R, Economics - para mais informações: help(economics).

```{r,cache=FALSE, warning=FALSE, fig.height= 5, fig.width=9}  
economics <- economics
```

* Histograma

```{r,cache=FALSE, warning=FALSE, fig.height= 5, fig.width=9}  
ggplot(economics, aes(psavert)) + geom_histogram(binwidth = diff(range(economics$psavert))/30) + geom_histogram(aes(fill=..count..)) # + scale_y_reverse() # + scale_fill_gradient("Count", low="red", high="blue")
```

* Gráfico de linha 

```{r,cache=FALSE, warning=FALSE, fig.height= 5, fig.width=9}  
ggplot(economics, aes(x=date, y=unemploy)) + geom_line() + xlab("Ano") + ylab("Desemprego (em milhares)") + ggtitle("Desemprego - Economics") # + geom_smooth() # + geom_smooth(method=lm)

ggplot(economics, aes(x=date, y=pop)) + geom_line() + xlab("Ano") + ylab("População (em milhares)") + ggtitle("População - Economics") # + geom_smooth() # + geom_smooth(method=lm)
```

* Gráfico de barra

```{r,cache=FALSE, warning=FALSE, fig.height= 5, fig.width=9}  
ggplot(iris, aes(Sepal.Width)) + geom_bar(aes(fill="pink")) 
```


* Gráficos de densidade

A função grid.arrange() necessita da instalação do pacote *gridExtra*.

```{r,cache=FALSE, warning=FALSE, fig.height= 5, fig.width=9}  

ggplot(economics) + geom_density(aes(pop), alpha = 0.6)

a <- ggplot(iris, aes(Sepal.Length, fill=Species)) + geom_density(alpha = 0.6) + facet_grid(. ~ Species)
b <- ggplot(iris, aes(Sepal.Width, fill=Species)) + geom_density(alpha = 0.6) + facet_grid(. ~ Species)
c <- ggplot(iris, aes(Petal.Length, fill=Species)) + geom_density(alpha = 0.6) + facet_grid(. ~ Species)
d <- ggplot(iris, aes(Sepal.Width, fill=Species)) + geom_density(alpha = 0.6) + facet_grid(. ~ Species)
grid.arrange(a, b, c, d) # gridExtra package required

e <- ggplot(iris, aes(Sepal.Length, fill=Species)) + geom_density(alpha = 0.6) 
f <- ggplot(iris, aes(Sepal.Width, fill=Species)) + geom_density(alpha = 0.6) 
g <- ggplot(iris, aes(Petal.Length, fill=Species)) + geom_density(alpha = 0.6)
h <- ggplot(iris, aes(Sepal.Width, fill=Species)) + geom_density(alpha = 0.6)

multiplot(e, f, g, h, cols=2) # multiplot function required

ggplot(iris, aes(Sepal.Length, fill = Species))+ geom_density(position = "stack", aes(y = ..count..))

ggplot(iris, aes(Sepal.Length, fill = Species))+ geom_density(position = "fill", aes(y = ..count..))
```


* Pode unir elementos, também!

```{r,cache=FALSE, warning=FALSE, fig.height= 5, fig.width=9}  
ggplot(iris, aes(Sepal.Length, Petal.Length, color = Species))+ geom_point() + geom_line()
```


> "All geometries begin with geom_, meaning you can get a full list using apropos() - apropos("^geom_")."

-------------------------------

### Referências:

* http://ggplot2.org/

* http://docs.ggplot2.org/current/ggplot.html

* http://docs.ggplot2.org/current/index.html

* http://en.wikipedia.org/wiki/Ggplot2

* Manual completo - http://cran.r-project.org/web/packages/ggplot2/ggplot2.pdf

* http://docs.ggplot2.org/0.9.3/aes.html

* **http://stackoverflow.com/questions/11657380/is-there-a-table-or-catalog-of-aesthetics-for-ggplot2**

* **http://www.ling.upenn.edu/~joseff/avml2012/#Section_1.1**

* http://blog.echen.me/2012/01/17/quick-introduction-to-ggplot2/

-------------------------------

> Todos os datasets utilizados neste tutorial são nativos do próprio R (iris e economics), isso significa que você pode replicá-lo em casa e fazer as modificações que deseje. :)
